apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: micromart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: mlmakhdoomi/micromart-auth:v1
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql://micromart:micromart123@postgres:5432/micromart"
            - name: JWT_SECRET
              value: "supersecretjwtkey123"