apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: micromart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "micromart"
            - name: POSTGRES_PASSWORD
              value: "micromart123"
            - name: POSTGRES_DB
              value: "micromart"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc